- hosts: terraform-ansible
  tasks:
    - name: installing python and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: installing deps with pip (django and djang rest)
      pip:
        virtualenv: /home/ubuntu/app/venv
        name:
          - django
          - djangorestframework
    - name: starting the project
      shell: ". /home/ubuntu/app/venv/bin/activate; django-admin startproject setup /home/ubuntu/app"
    - name: change hosts
      lineinfile:
        path: /home/ubuntu/app/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes
