- hosts: terraform-ansible
  tasks:
    - name: touch file
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Make with terraform and ansible, hehe boe</h1>
    - name: start server
      shell: "nohup busybox httpd -f -p 8080 &"
